openapi: 3.0.1
info:
  title: Chat Service API
  description: An API to manage group chats, direct messages, and message interactions.
  version: 1.0.0

paths:
  /chat/groups:
    get:
      summary: Retrieve all accessible groups
      description: Fetches all groups that the authenticated user has access to.
      responses:
        '200':
          description: Successfully retrieved the list of groups
          content:
            application/json:
              schema:
                type: object
                properties:
                  chats:
                    type: array
                    items:
                      $ref: '#/components/schemas/Chat'
        '404':
          description: No groups found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "No groups were found"
        '401':
          description: Unauthorized access - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden - Insufficient permissions"
    post:
      summary: Create a new group
      description: Creates a new group with the provided title and list of members.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: The title of the new group.
                  example: "Team Planning"
                members:
                  type: array
                  items:
                    $ref: '#/components/schemas/ID'
                  description: List of member IDs to be added to the group.
                  example: 
                    - "11111111-11111111-11111111-11111111"
                    - "22222222-22222222-22222222-22222222"
      responses:
        '201':
          description: Group created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '400':
          description: Bad request - Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid group data provided."
        '401':
          description: Unauthorized access - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden - Insufficient permissions"

  /chat/groups/{groupId}/members:
    post:
      summary: Add a user to a group
      description: Adds a user to the specified group by their user ID.
      parameters:
        - name: groupId
          in: path
          required: true
          description: The ID of the group to which the user will be added.
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: The ID of the user to be added to the group.
                  example: "33333333-33333333-33333333-33333333"
      responses:
        '200':
          description: User successfully added to the group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '400':
          description: Bad request - Invalid user ID or group ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid user or group ID."
        '401':
          description: Unauthorized access - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden - Insufficient permissions"
        '404':
          description: Group or user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Group or user not found."

  /chat/groups/{groupId}/members/{userId}:
    delete:
      summary: Remove a user from a group
      description: Removes a user from the specified group by their user ID.
      parameters:
        - name: groupId
          in: path
          required: true
          description: The ID of the group from which the user will be removed.
          schema:
            $ref: '#/components/schemas/ID'
        - name: userId
          in: path
          required: true
          description: The ID of the user to be removed from the group.
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        '200':
          description: User successfully removed from the group
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chat'
        '400':
          description: Bad request - Invalid user ID or group ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid user or group ID."
        '401':
          description: Unauthorized access - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden - Insufficient permissions"
        '404':
          description: Group or user not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Group or user not found."
  /chat/groups/{groupId}/messages:
    get:
      summary: Retrieve all messages from a group
      description: Fetches all messages from the specified group.
      parameters:
        - name: groupId
          in: path
          required: true
          description: The ID of the group to retrieve messages from.
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        '200':
          description: Successfully retrieved the list of messages
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '404':
          description: Group not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Group not found."
        '401':
          description: Unauthorized access - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden - Insufficient permissions"
    post:
      summary: Send a message to a group
      description: Sends a message to the specified group.
      parameters:
        - name: groupId
          in: path
          required: true
          description: The ID of the group where the message will be sent.
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The content of the message.
                  example: "Hello team!"
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Bad request - Invalid message content or group ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid message content."
        '401':
          description: Unauthorized access - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden - Insufficient permissions"
        '404':
          description: Group not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Group not found."
  /chat/messages/{messageId}/react:
    post:
      summary: Send a reaction to a message
      description: Sends a reaction to the specified message.
      parameters:
        - name: messageId
          in: path
          required: true
          description: The message of the reaction.
          schema:
            $ref: '#/components/schemas/ID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The content of the message.
                  example: "Hello team!"
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Bad request - Invalid message content or group ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid message content."
        '401':
          description: Unauthorized access - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden - Insufficient permissions"
        '404':
          description: Group not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Group not found."
    delete:
      summary: Delete a reaction from a message
      description: Delete a reaction from the specified message.
      parameters:
        - name: messageId
          in: path
          required: true
          description: The message of the reaction.
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        '200':
          description: Message reaction successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Message reaction deleted successfully."
        '404':
          description: Reaction not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Reaction not found."
        '401':
          description: Unauthorized access - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden - Insufficient permissions"

  /chat/groups/{groupId}/messages/{messageId}:
    delete:
      summary: Delete a message from a group
      description: Deletes a specific message from a group.
      parameters:
        - name: groupId
          in: path
          required: true
          description: The ID of the group from which the message will be deleted.
          schema:
            $ref: '#/components/schemas/ID'
        - name: messageId
          in: path
          required: true
          description: The ID of the message to be deleted.
          schema:
            $ref: '#/components/schemas/ID'
      responses:
        '200':
          description: Message successfully deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Message deleted successfully."
        '404':
          description: Message or group not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Message or group not found."
        '401':
          description: Unauthorized access - Insufficient permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Forbidden - Insufficient permissions"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ID:
      type: string
      example: "00000000-00000000-00000000-00000000"

    Chat:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ID'
        title:
          type: string
          example: "Team Meetings"
        members:
          type: array
          items:
            $ref: '#/components/schemas/Member'

    Message:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ID'
        content:
          type: string
          example: "Hello team!"
        sender:
          $ref: '#/components/schemas/Member'
        timestamp:
          type: string
          format: date-time
          example: "2024-11-25T10:00:00Z"

    Member:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ID'
        name:
          type: string
          example: "Max"

security:
  - BearerAuth: []
